// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace IngresoStockServicioTecnicoRetail.Models;

public partial class ESCORIALContext : DbContext
{
    public ESCORIALContext()
    {
    }

    public ESCORIALContext(DbContextOptions<ESCORIALContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Solitudcambioretailpicking> Solitudcambioretailpickings { get; set; }

    public virtual DbSet<VItemsolicitud> VItemsolicituds { get; set; }

    public virtual DbSet<VProducto> VProductos { get; set; }

    public virtual DbSet<VTrsolicitud> VTrsolicituds { get; set; }

    public virtual DbSet<VUdItemsolreparacionretail> VUdItemsolreparacionretails { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseNpgsql("Host=10.90.98.7;Database=ESCORIAL;Username=escoaplicf;Password=H65u4.hrt;Persist Security Info=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("fuzzystrmatch")
            .HasPostgresExtension("hstore")
            .HasPostgresExtension("ltree")
            .HasPostgresExtension("pg_stat_statements")
            .HasPostgresExtension("pgstattuple")
            .HasPostgresExtension("unaccent");

        modelBuilder.Entity<Solitudcambioretailpicking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("solitudcambioretailpicking_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ProcesadoCalipso).HasDefaultValue(false);
        });

        modelBuilder.Entity<VItemsolicitud>(entity =>
        {
            entity.ToView("v_itemsolicitud");
        });

        modelBuilder.Entity<VProducto>(entity =>
        {
            entity.ToView("v_producto");
        });

        modelBuilder.Entity<VTrsolicitud>(entity =>
        {
            entity.ToView("v_trsolicitud");
        });

        modelBuilder.Entity<VUdItemsolreparacionretail>(entity =>
        {
            entity.ToView("v_ud_itemsolreparacionretail");
        });
        modelBuilder.HasSequence("aux_suceso_inc_seq");
        modelBuilder.HasSequence("hibernate_sequence", "web");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}