// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IngresoStockServicioTecnicoRetail.Models;

[Table("solitudcambioretailpicking", Schema = "web")]
public partial class Solitudcambioretailpicking
{
    [Column("fecha_ingreso", TypeName = "timestamp without time zone")]
    public DateTime? FechaIngreso { get; set; }

    [Column("solicitud_id")]
    public Guid? SolicitudId { get; set; }

    [Column("itemsolicitud_id")]
    public Guid? ItemsolicitudId { get; set; }

    [Column("codigo_producto")]
    [StringLength(100)]
    public string CodigoProducto { get; set; }

    [Column("serie_producto")]
    [StringLength(100)]
    public string SerieProducto { get; set; }

    [Column("procesado_calipso")]
    public bool? ProcesadoCalipso { get; set; }

    [Column("fecha_procesado_calipso", TypeName = "timestamp without time zone")]
    public DateTime? FechaProcesadoCalipso { get; set; }

    [Key]
    [Column("id")]
    public Guid Id { get; set; }
}