// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IngresoStockServicioTecnicoRetail.Models;

[Keyless]
public partial class VItemsolicitud
{
    [Column("id")]
    public Guid? Id { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("referencia_id")]
    public Guid? ReferenciaId { get; set; }

    [Column("descripcion")]
    [StringLength(150)]
    public string Descripcion { get; set; }

    [Column("mecanismoscalculoitemtr_id")]
    public Guid? MecanismoscalculoitemtrId { get; set; }

    [Column("placeowner_id")]
    public Guid? PlaceownerId { get; set; }

    [Column("detalle")]
    [StringLength(100)]
    public string Detalle { get; set; }

    [Column("impuestositemtransaccion_id")]
    public Guid? ImpuestositemtransaccionId { get; set; }

    [Column("imputacioncontable_id")]
    public Guid? ImputacioncontableId { get; set; }

    [Column("observacion_id")]
    public Guid? ObservacionId { get; set; }

    [Column("centrocostos_id")]
    public Guid? CentrocostosId { get; set; }

    [Column("centrocostosori_id")]
    public Guid? CentrocostosoriId { get; set; }

    [Column("tipodistribucioncencos_id")]
    public Guid? TipodistribucioncencosId { get; set; }

    [Column("itempendiente_id")]
    public Guid? ItempendienteId { get; set; }

    [Column("cancelacion_id")]
    public Guid? CancelacionId { get; set; }

    [Column("infra")]
    [Precision(22, 10)]
    public decimal? Infra { get; set; }

    [Column("supra")]
    [Precision(22, 10)]
    public decimal? Supra { get; set; }

    [Column("tipotransaccion_id")]
    public Guid? TipotransaccionId { get; set; }

    [Column("momentotr")]
    [StringLength(17)]
    public string Momentotr { get; set; }

    [Column("numerodocumento")]
    [StringLength(20)]
    public string Numerodocumento { get; set; }

    [Column("fechadocumento")]
    [StringLength(17)]
    public string Fechadocumento { get; set; }

    [Column("nombreoriginantetr")]
    [StringLength(100)]
    public string Nombreoriginantetr { get; set; }

    [Column("nombredestinatariotr")]
    [StringLength(100)]
    public string Nombredestinatariotr { get; set; }

    [Column("originantetr_id")]
    public Guid? OriginantetrId { get; set; }

    [Column("destinatariotr_id")]
    public Guid? DestinatariotrId { get; set; }

    [Column("compania_id")]
    public Guid? CompaniaId { get; set; }

    [Column("unidadoperativa_id")]
    public Guid? UnidadoperativaId { get; set; }

    [Column("nombretr")]
    [StringLength(60)]
    public string Nombretr { get; set; }

    [Column("estadotr")]
    [StringLength(1)]
    public string Estadotr { get; set; }

    [Column("nombrereferencia")]
    [StringLength(100)]
    public string Nombrereferencia { get; set; }

    [Column("totaltr")]
    [Precision(22, 10)]
    public decimal? Totaltr { get; set; }

    [Column("nombretotaltr")]
    [StringLength(30)]
    public string Nombretotaltr { get; set; }

    [Column("numeroitem")]
    public int? Numeroitem { get; set; }

    [Column("cotizacion")]
    [Precision(22, 10)]
    public decimal? Cotizacion { get; set; }

    [Column("monedabase_id")]
    public Guid? MonedabaseId { get; set; }

    [Column("cotizacionconversion")]
    [Precision(22, 10)]
    public decimal? Cotizacionconversion { get; set; }

    [Column("suma_id")]
    public Guid? SumaId { get; set; }

    [Column("suma2_importe")]
    [Precision(22, 10)]
    public decimal? Suma2Importe { get; set; }

    [Column("suma2_unidadvalorizacion_id")]
    public Guid? Suma2UnidadvalorizacionId { get; set; }

    [Column("suma2_momento")]
    [StringLength(17)]
    public string Suma2Momento { get; set; }

    [Column("suma2_nombre")]
    [StringLength(30)]
    public string Suma2Nombre { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("composicioncostorecurso_id")]
    public Guid? ComposicioncostorecursoId { get; set; }

    [Column("proyecto_id")]
    public Guid? ProyectoId { get; set; }

    [Column("discriminadorcontable1_id")]
    public Guid? Discriminadorcontable1Id { get; set; }

    [Column("discriminadorcontable2_id")]
    public Guid? Discriminadorcontable2Id { get; set; }

    [Column("discriminadorcontable3_id")]
    public Guid? Discriminadorcontable3Id { get; set; }

    [Column("subsucursal_id")]
    public Guid? SubsucursalId { get; set; }

    [Column("nombregrupoeconomico")]
    [StringLength(100)]
    public string Nombregrupoeconomico { get; set; }

    [Column("discriminadorcontable4_id")]
    public Guid? Discriminadorcontable4Id { get; set; }

    [Column("discriminadorcontable5_id")]
    public Guid? Discriminadorcontable5Id { get; set; }

    [Column("discriminadorcontable6_id")]
    public Guid? Discriminadorcontable6Id { get; set; }

    [Column("discriminadorcontable7_id")]
    public Guid? Discriminadorcontable7Id { get; set; }

    [Column("discriminadorcontable8_id")]
    public Guid? Discriminadorcontable8Id { get; set; }

    [Column("discriminadorcontable9_id")]
    public Guid? Discriminadorcontable9Id { get; set; }

    [Column("discriminadorcontable10_id")]
    public Guid? Discriminadorcontable10Id { get; set; }

    [Column("torneo_id")]
    public Guid? TorneoId { get; set; }

    [Column("division_id")]
    public Guid? DivisionId { get; set; }

    [Column("categoria_id")]
    public Guid? CategoriaId { get; set; }

    [Column("partido_id")]
    public Guid? PartidoId { get; set; }

    [Column("club_id")]
    public Guid? ClubId { get; set; }

    [Column("esquemaoperativo_id")]
    public Guid? EsquemaoperativoId { get; set; }

    [Column("nombreesquemaoperativo")]
    [StringLength(50)]
    public string Nombreesquemaoperativo { get; set; }

    [Column("hito_id")]
    public Guid? HitoId { get; set; }

    [Column("cantidad_id")]
    public Guid? CantidadId { get; set; }

    [Column("valor_id")]
    public Guid? ValorId { get; set; }

    [Column("cantidadnolineal_id")]
    public Guid? CantidadnolinealId { get; set; }

    [Column("total_id")]
    public Guid? TotalId { get; set; }

    [Column("unidadmedida_id")]
    public Guid? UnidadmedidaId { get; set; }

    [Column("unidadmedidanolineal_id")]
    public Guid? UnidadmedidanolinealId { get; set; }

    [Column("referenciatipo_id")]
    public Guid? ReferenciatipoId { get; set; }

    [Column("totalsindescuentos")]
    [Precision(22, 10)]
    public decimal? Totalsindescuentos { get; set; }

    [Column("cantidad2_cantidad")]
    [Precision(22, 10)]
    public decimal? Cantidad2Cantidad { get; set; }

    [Column("cantidad2_unidadmedida_id")]
    public Guid? Cantidad2UnidadmedidaId { get; set; }

    [Column("valor2_importe")]
    [Precision(22, 10)]
    public decimal? Valor2Importe { get; set; }

    [Column("valor2_unidadvalorizacion_id")]
    public Guid? Valor2UnidadvalorizacionId { get; set; }

    [Column("valor2_momento")]
    [StringLength(17)]
    public string Valor2Momento { get; set; }

    [Column("valor2_nombre")]
    [StringLength(30)]
    public string Valor2Nombre { get; set; }

    [Column("cnolineal2_cantidad")]
    [Precision(22, 10)]
    public decimal? Cnolineal2Cantidad { get; set; }

    [Column("cnolineal2_unidadmedida_id")]
    public Guid? Cnolineal2UnidadmedidaId { get; set; }

    [Column("total2_importe")]
    [Precision(22, 10)]
    public decimal? Total2Importe { get; set; }

    [Column("total2_unidadvalorizacion_id")]
    public Guid? Total2UnidadvalorizacionId { get; set; }

    [Column("total2_momento")]
    [StringLength(17)]
    public string Total2Momento { get; set; }

    [Column("total2_nombre")]
    [StringLength(30)]
    public string Total2Nombre { get; set; }

    [Column("preciooriginal")]
    [Precision(22, 10)]
    public decimal? Preciooriginal { get; set; }

    [Column("monedaoriginal_id")]
    public Guid? MonedaoriginalId { get; set; }

    [Column("cotizacionoriginal")]
    [Precision(22, 10)]
    public decimal? Cotizacionoriginal { get; set; }

    [Column("preciounitariofinal")]
    [Precision(22, 10)]
    public decimal? Preciounitariofinal { get; set; }

    [Column("listaprecio_id")]
    public Guid? ListaprecioId { get; set; }

    [Column("porcentajebonificacion")]
    [Precision(22, 10)]
    public decimal? Porcentajebonificacion { get; set; }

    [Column("compromisopago_id")]
    public Guid? CompromisopagoId { get; set; }

    [Column("importebonificacion_id")]
    public Guid? ImportebonificacionId { get; set; }

    [Column("fechaentrega")]
    [StringLength(8)]
    public string Fechaentrega { get; set; }

    [Column("importedescuento_id")]
    public Guid? ImportedescuentoId { get; set; }

    [Column("cantboni2_cantidad")]
    [Precision(22, 10)]
    public decimal? Cantboni2Cantidad { get; set; }

    [Column("cantboni2_unidadmedida_id")]
    public Guid? Cantboni2UnidadmedidaId { get; set; }

    [Column("impboni2_importe")]
    [Precision(22, 10)]
    public decimal? Impboni2Importe { get; set; }

    [Column("impboni2_unidadvalorizacion_id")]
    public Guid? Impboni2UnidadvalorizacionId { get; set; }

    [Column("impboni2_momento")]
    [StringLength(17)]
    public string Impboni2Momento { get; set; }

    [Column("impboni2_nombre")]
    [StringLength(30)]
    public string Impboni2Nombre { get; set; }

    [Column("impdesc2_importe")]
    [Precision(22, 10)]
    public decimal? Impdesc2Importe { get; set; }

    [Column("impdesc2_unidadvalorizacion_id")]
    public Guid? Impdesc2UnidadvalorizacionId { get; set; }

    [Column("impdesc2_momento")]
    [StringLength(17)]
    public string Impdesc2Momento { get; set; }

    [Column("impdesc2_nombre")]
    [StringLength(30)]
    public string Impdesc2Nombre { get; set; }

    [Column("domicilio_id")]
    public Guid? DomicilioId { get; set; }

    [Column("codigoalternativo_id")]
    public Guid? CodigoalternativoId { get; set; }

    [Column("importebonificado")]
    [Precision(22, 10)]
    public decimal? Importebonificado { get; set; }

    [Column("lote_id")]
    public Guid? LoteId { get; set; }

    [Column("serie_id")]
    public Guid? SerieId { get; set; }

    [Column("seriedestino_id")]
    public Guid? SeriedestinoId { get; set; }

    [Column("envase_id")]
    public Guid? EnvaseId { get; set; }

    [Column("paquete_id")]
    public Guid? PaqueteId { get; set; }

    [Column("datoscomplementarios_id")]
    public Guid? DatoscomplementariosId { get; set; }

    [Column("unidadnegocio_id")]
    public Guid? UnidadnegocioId { get; set; }

    [Column("cuentacontable_id")]
    public Guid? CuentacontableId { get; set; }

    [Column("domicilioentrega_id")]
    public Guid? DomicilioentregaId { get; set; }

    [Column("bultos")]
    public int? Bultos { get; set; }

    [Column("depositoori_id")]
    public Guid? DepositooriId { get; set; }

    [Column("depositodes_id")]
    public Guid? DepositodesId { get; set; }

    [Column("despacho_id")]
    public Guid? DespachoId { get; set; }

    [Column("ubicacionori_id")]
    public Guid? UbicacionoriId { get; set; }

    [Column("ubicaciondes_id")]
    public Guid? UbicaciondesId { get; set; }

    [Column("peso")]
    [Precision(22, 10)]
    public decimal? Peso { get; set; }

    [Column("volumen")]
    [Precision(22, 10)]
    public decimal? Volumen { get; set; }

    [Column("kit_id")]
    public Guid? KitId { get; set; }

    [Column("textoevaluacion")]
    [StringLength(50)]
    public string Textoevaluacion { get; set; }

    [Column("cpvs1")]
    [StringLength(20)]
    public string Cpvs1 { get; set; }

    [Column("cpvs2")]
    [StringLength(20)]
    public string Cpvs2 { get; set; }

    [Column("cpvn1")]
    [Precision(22, 10)]
    public decimal? Cpvn1 { get; set; }

    [Column("cpvn2")]
    [Precision(22, 10)]
    public decimal? Cpvn2 { get; set; }

    [Column("fechadevengamiento")]
    [StringLength(8)]
    public string Fechadevengamiento { get; set; }

    [Column("itemconsolidado_id")]
    public Guid? ItemconsolidadoId { get; set; }

    [Column("vence")]
    [StringLength(17)]
    public string Vence { get; set; }

    [Column("breservation_id")]
    public Guid? BreservationId { get; set; }

    [Column("relacioneswosol_id")]
    public Guid? RelacioneswosolId { get; set; }

    [Column("referenciaserviciomant_id")]
    public Guid? ReferenciaserviciomantId { get; set; }

    [Column("dimensionalidad_id")]
    public Guid? DimensionalidadId { get; set; }

    [Column("proveedordefault_id")]
    public Guid? ProveedordefaultId { get; set; }
}