// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IngresoStockServicioTecnicoRetail.Models;

[Keyless]
public partial class VTrsolicitud
{
    [Column("id")]
    public Guid? Id { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("lockstatus")]
    public int? Lockstatus { get; set; }

    [Column("checksoptimisticupdates")]
    [StringLength(40)]
    public string Checksoptimisticupdates { get; set; }

    [Column("itemstransaccion_id")]
    public Guid? ItemstransaccionId { get; set; }

    [Column("originante_id")]
    public Guid? OriginanteId { get; set; }

    [Column("estado")]
    [StringLength(1)]
    public string Estado { get; set; }

    [Column("flag_id")]
    public Guid? FlagId { get; set; }

    [Column("destinatario_id")]
    public Guid? DestinatarioId { get; set; }

    [Column("nombredestinatario")]
    [StringLength(100)]
    public string Nombredestinatario { get; set; }

    [Column("codigodestinatario")]
    [StringLength(50)]
    public string Codigodestinatario { get; set; }

    [Column("nombreoriginante")]
    [StringLength(100)]
    public string Nombreoriginante { get; set; }

    [Column("numerodocumento")]
    [StringLength(20)]
    public string Numerodocumento { get; set; }

    [Column("numerodocumentointerno")]
    [StringLength(12)]
    public string Numerodocumentointerno { get; set; }

    [Column("fechaactual")]
    [StringLength(17)]
    public string Fechaactual { get; set; }

    [Column("compania_id")]
    public Guid? CompaniaId { get; set; }

    [Column("unidadoperativa_id")]
    public Guid? UnidadoperativaId { get; set; }

    [Column("numerador_id")]
    public Guid? NumeradorId { get; set; }

    [Column("tipotransaccion_id")]
    public Guid? TipotransaccionId { get; set; }

    [Column("momento")]
    [StringLength(17)]
    public string Momento { get; set; }

    [Column("totales_id")]
    public Guid? TotalesId { get; set; }

    [Column("generadapor_id")]
    public Guid? GeneradaporId { get; set; }

    [Column("nombre")]
    [StringLength(60)]
    public string Nombre { get; set; }

    [Column("mecanismoscalculotr_id")]
    public Guid? MecanismoscalculotrId { get; set; }

    [Column("definicionesmcalculoitem_id")]
    public Guid? DefinicionesmcalculoitemId { get; set; }

    [Column("vinculostransaccionales_id")]
    public Guid? VinculostransaccionalesId { get; set; }

    [Column("datosanexos_id")]
    public Guid? DatosanexosId { get; set; }

    [Column("detalle")]
    [StringLength(300)]
    public string Detalle { get; set; }

    [Column("mediotransporte_id")]
    public Guid? MediotransporteId { get; set; }

    [Column("impuestostransaccion_id")]
    public Guid? ImpuestostransaccionId { get; set; }

    [Column("definicionesimpuestositem_id")]
    public Guid? DefinicionesimpuestositemId { get; set; }

    [Column("imputacioncontable_id")]
    public Guid? ImputacioncontableId { get; set; }

    [Column("external_id")]
    [StringLength(60)]
    public string ExternalId { get; set; }

    [Column("centrocostos_id")]
    public Guid? CentrocostosId { get; set; }

    [Column("tipodistribucioncencos_id")]
    public Guid? TipodistribucioncencosId { get; set; }

    [Column("referenciatransaccion_id")]
    public Guid? ReferenciatransaccionId { get; set; }

    [Column("atributosauxiliares_id")]
    public Guid? AtributosauxiliaresId { get; set; }

    [Column("trextension_id")]
    public Guid? TrextensionId { get; set; }

    [Column("usuario")]
    [StringLength(30)]
    public string Usuario { get; set; }

    [Column("activa")]
    public bool? Activa { get; set; }

    [Column("cotizacion")]
    [Precision(22, 10)]
    public decimal? Cotizacion { get; set; }

    [Column("fechaultimoestado")]
    [StringLength(17)]
    public string Fechaultimoestado { get; set; }

    [Column("moneda_id")]
    public Guid? MonedaId { get; set; }

    [Column("nombremoneda")]
    [StringLength(40)]
    public string Nombremoneda { get; set; }

    [Column("totaltr")]
    [StringLength(30)]
    public string Totaltr { get; set; }

    [Column("valortotal")]
    [Precision(22, 10)]
    public decimal? Valortotal { get; set; }

    [Column("finrelacion")]
    public bool? Finrelacion { get; set; }

    [Column("transicion_id")]
    public Guid? TransicionId { get; set; }

    [Column("nota")]
    [StringLength(100)]
    public string Nota { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("vinculotr_id")]
    public Guid? VinculotrId { get; set; }

    [Column("monedabase_id")]
    public Guid? MonedabaseId { get; set; }

    [Column("proyecto_id")]
    public Guid? ProyectoId { get; set; }

    [Column("itemsconsolidacion_id")]
    public Guid? ItemsconsolidacionId { get; set; }

    [Column("numeradorinterno_id")]
    public Guid? NumeradorinternoId { get; set; }

    [Column("discriminadorcontable1_id")]
    public Guid? Discriminadorcontable1Id { get; set; }

    [Column("discriminadorcontable2_id")]
    public Guid? Discriminadorcontable2Id { get; set; }

    [Column("discriminadorcontable3_id")]
    public Guid? Discriminadorcontable3Id { get; set; }

    [Column("discriminadorcontable4_id")]
    public Guid? Discriminadorcontable4Id { get; set; }

    [Column("discriminadorcontable5_id")]
    public Guid? Discriminadorcontable5Id { get; set; }

    [Column("discriminadorcontable6_id")]
    public Guid? Discriminadorcontable6Id { get; set; }

    [Column("discriminadorcontable7_id")]
    public Guid? Discriminadorcontable7Id { get; set; }

    [Column("discriminadorcontable8_id")]
    public Guid? Discriminadorcontable8Id { get; set; }

    [Column("discriminadorcontable9_id")]
    public Guid? Discriminadorcontable9Id { get; set; }

    [Column("discriminadorcontable10_id")]
    public Guid? Discriminadorcontable10Id { get; set; }

    [Column("puntoventa_id")]
    public Guid? PuntoventaId { get; set; }

    [Column("subsucursal_id")]
    public Guid? SubsucursalId { get; set; }

    [Column("talonario_id")]
    public Guid? TalonarioId { get; set; }

    [Column("arearesp_id")]
    public Guid? ArearespId { get; set; }

    [Column("fechavencimientocp")]
    [StringLength(8)]
    public string Fechavencimientocp { get; set; }

    [Column("nombregrupoeconomico")]
    [StringLength(100)]
    public string Nombregrupoeconomico { get; set; }

    [Column("ruta_id")]
    public Guid? RutaId { get; set; }

    [Column("esquemaoperativo_id")]
    public Guid? EsquemaoperativoId { get; set; }

    [Column("nombreesquemaoperativo")]
    [StringLength(50)]
    public string Nombreesquemaoperativo { get; set; }

    [Column("secuenciaentrega")]
    public int? Secuenciaentrega { get; set; }

    [Column("listaprecio_id")]
    public Guid? ListaprecioId { get; set; }

    [Column("domicilio_id")]
    public Guid? DomicilioId { get; set; }

    [Column("porcentajesdescuento_id")]
    public Guid? PorcentajesdescuentoId { get; set; }

    [Column("suma_id")]
    public Guid? SumaId { get; set; }

    [Column("tipopago_id")]
    public Guid? TipopagoId { get; set; }

    [Column("totaldescuento_id")]
    public Guid? TotaldescuentoId { get; set; }

    [Column("subtotal_id")]
    public Guid? SubtotalId { get; set; }

    [Column("subtotalimporte")]
    [Precision(22, 10)]
    public decimal? Subtotalimporte { get; set; }

    [Column("total_id")]
    public Guid? TotalId { get; set; }

    [Column("compromisopago_id")]
    public Guid? CompromisopagoId { get; set; }

    [Column("fechaentrega")]
    [StringLength(8)]
    public string Fechaentrega { get; set; }

    [Column("descripdescuentos")]
    [StringLength(60)]
    public string Descripdescuentos { get; set; }

    [Column("domicilioentrega_id")]
    public Guid? DomicilioentregaId { get; set; }

    [Column("fechaven2")]
    [StringLength(8)]
    public string Fechaven2 { get; set; }

    [Column("importefechaven2")]
    [Precision(22, 10)]
    public decimal? Importefechaven2 { get; set; }

    [Column("fechaven3")]
    [StringLength(8)]
    public string Fechaven3 { get; set; }

    [Column("importefechaven3")]
    [Precision(22, 10)]
    public decimal? Importefechaven3 { get; set; }

    [Column("fechalistaprecio")]
    [StringLength(17)]
    public string Fechalistaprecio { get; set; }

    [Column("monedaoriginal_id")]
    public Guid? MonedaoriginalId { get; set; }

    [Column("cotizacionoriginal")]
    [Precision(22, 10)]
    public decimal? Cotizacionoriginal { get; set; }

    [Column("pesototal")]
    [Precision(22, 10)]
    public decimal? Pesototal { get; set; }

    [Column("volumentotal")]
    [Precision(22, 10)]
    public decimal? Volumentotal { get; set; }

    [Column("totalbultos")]
    [Precision(22, 10)]
    public decimal? Totalbultos { get; set; }

    [Column("tasainteres")]
    [Precision(22, 10)]
    public decimal? Tasainteres { get; set; }

    [Column("descuentosacordadostr_id")]
    public Guid? DescuentosacordadostrId { get; set; }

    [Column("motivotraslado_id")]
    public Guid? MotivotrasladoId { get; set; }

    [Column("responsable_id")]
    public Guid? ResponsableId { get; set; }

    [Column("vence")]
    [StringLength(17)]
    public string Vence { get; set; }

    [Column("referenciaplan_id")]
    public Guid? ReferenciaplanId { get; set; }

    [Column("tipodimension_id")]
    public Guid? TipodimensionId { get; set; }
}