// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IngresoStockServicioTecnicoRetail.Models;

[Keyless]
public partial class VUdItemsolreparacionretail
{
    [Column("id")]
    public Guid? Id { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("serieproducto")]
    [StringLength(200)]
    public string Serieproducto { get; set; }

    [Column("ingreso_manual")]
    public bool? IngresoManual { get; set; }
}